on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'
  
      - name: Install pak
        run: |
          install.packages(c("pak", "renv"))
        shell: Rscript {0}
        
      - name: Install R packages
        run: |
          pak::pkg_install(pkg = renv::dependencies()$Package)
        shell: Rscript {0}

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto website
        run: |
          quarto render

      - name: Publish to GitHub Pages
        if: github.event_name != 'pull_request'
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
          publish_dir: ./_site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
